### ISSUE TITLE
Update download page with YugabyteDB Voyager install instructions.

### ISSUE THREAD

**Issue by aishwarya24** [yugabyte/get-started-page#77]
Summary of a list of changes to the page.
- Include a new tab for YugabyteDB Voyager : https://download.yugabyte.com/#/
- Change the third tab from Fully-Managed Cloud to YugabyteDB Managed.
- The fourth tab should be YugabyteDB Voyager(small font) and Migrate(big font)
- Provide a list of operating systems we support for Voyager.
- Provide instructions for each installation option.
- screenshots (if necessary)

**Comment by polarweasel** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/538384/207138672-2d39a5e9-600a-4c99-a4fb-ffb2b7be1f1f.png">

**Comment by polarweasel** [comment]
This is blocked by https://github.com/yugabyte/yugabyte-db/pull/15348. Once that's merged, we've got all the content we need for this one.
